### ISSUE TITLE
Issue Types selector keeps spinning

### ISSUE THREAD

**Issue by heiko-braun** [EricWittmann/jiralist#3]
When creating a new list, the type selector keeps loading endlessly

![screen shot 2015-06-30 at 10 42 22](https://cloud.githubusercontent.com/assets/369380/8427035/b232fd9e-1f14-11e5-860c-22e37a290732.png)

**Comment by heiko-braun** [comment]
Ah, the project doesn't use the default issue types.

**Comment by EricWittmann** [comment]
It really never resolves?  It's just doing an API call to retrieve the set of issue types... :(

**Comment by EricWittmann** [comment]
I'll try to reproduce!

**Comment by heiko-braun** [comment]
maybe it's lack of privileges on the EAP project?

**Comment by EricWittmann** [comment]
Looks like no issue types get returned for that project.

**Comment by EricWittmann** [comment]
Yeah looks like if you don't have privs to the project then the API call to return the issue types returns nothing.  I'll add a fix. :)

**Comment by heiko-braun** [comment]
These are the types:

![screen shot 2015-06-30 at 13 39 04](https://cloud.githubusercontent.com/assets/369380/8430018/62ac2dd6-1f2d-11e5-9879-19cee2c53825.png)

**Comment by heiko-braun** [comment]
but it think it's an edge case

**Comment by EricWittmann** [comment]
It's supposed to pull back the issue types from the /issue/createmeta API endpoint so that it doesn't have to hard-code them (which would obviously be bad).  Here is the endpoint it tries to hit:

https://issues.jboss.org/rest/api/2/issue/createmeta?projectKeys=EAP7

This returns _nothing_ for the EAP7 project.  Not even the name and id of the project.  If you try another project e.g.:

https://issues.jboss.org/rest/api/2/issue/createmeta?projectKeys=APIMAN

You'll get back some meta-data including the issue types.  I'm not 100% sure why nothing comes back for EAP7.

I will at least fix the "forever spinning" problem - but not the root issue of why the issue types don't get returned for that particular project (at least when using _my_ credentials).  :)

**Comment by EricWittmann** [comment]
Pushing the fix to openshift now.

**Comment by EricWittmann** [comment]
The forever-spinning should be fixed now - which will allow you to create the list.  Not sure what else might go wrong later on without the list of issue types.  :)  In particular you may not be able to successfully create an issue.  That's the main purpose of the list of issue types.

**Comment by heiko-braun** [comment]
tnx eric
